config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"

  get '/about', to: 'pages#about'

  get 'new_user_session', to: 'devise/sessions#new'
  
  delete 'destroy_user_session', to: 'devise/sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy #making association to post. if post gets deleted, comment gets deleted from database as well.
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
	  @posts = Post.all.order('created_at DESC')
	end

	def new
	  @post = current_user.posts.build
	end

	def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
    	redirect_to @post
    else
    	render 'new' 

    	#render instead of redirect, because redirect would do an entirely
    	#new http request and reset the page, losing unsubmitted blog post.
    end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private
	  def post_params
	  	params.require(:post).permit(:title, :body)
	  end

	  def find_post
	  	@post = Post.find(params[:id])
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.comment_content
		%p.comment_name.strong
			= comment.name
		%p.comment_body
			= comment.body
		%p.comment_time
			= "#{time_ago_in_words(comment.created_at)} Ago."

app/views/comments/_form.html.haml
= form_for ([@post, @post.comments.build]) do |f|
  %p
  = f.label :name
  = f.text_field :name
  %p
  = f.label :body
  = f.text_area :body
  %p
  = f.submit "Post Comment"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ginny's Rails Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Merriweather:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    
  </head>

  <body>
  	<div id="sidebar">
  	  <div id="logo">
  	  	<%= link_to root_path do %>
        <%= image_tag "rubylogo.png" %>  
  	  	<% end %>
  	  </div>

      

  	
     <ul>
     	<li class="category">Website</li>
     	<li><%= link_to "Blog", root_path %></li>
     	<li><%= link_to "About", about_path %></li>
     </ul>

     <ul>
     	<li class="category">Social</li>
     	<li><a href="https://twitter.com/ginnynumberone">Twitter</a></li>
     	<li><a href="https://instagram.com/ginnynumberone">Instagram</a></li>
     	<li><a href="https://github.com/mangatgrinpal">GitHub</a></li>
     	<li><a href="mailto:mangatgrinpal@gmail.com">Email</a></li>
     </ul>

     
  </div>

<div id="main_content">
	<div id="header">
    <% if current_page?(root_path) %>
	     <p>All Posts</p>
    <% elsif current_page?(about_path) %>
       <p>About</p>
    <% else %>
      <%= link_to "Back to All Posts", root_path %>
      <% end %>

<% if user_signed_in? %>
		<div class="buttons">
			<button class="button"><%= link_to "New Post", new_post_path %></button>
			<button class="button"><%= link_to "Log Out", destroy_user_session_path, :method => :delete %>  
      </button>
		</div>
    <% end %>
	</div>

	<% flash.each do |name, msg| %>
	  <%= content_tag(:div, msg, class: "alert") %>
	<% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.haml
#page_wrapper
  #profile_image
    = image_tag "about.JPG"

  #content
    %h1 Hello, I'm Ginny Mangat
    %p Welcome to my Rails blog! 
    %p This is the second rails application that I've put together with the help of online resources. I graduated from University of California - Santa Cruz in 2016 with a B.S. in Chemistry... consider this a career change.
    %p You can find me on Twitter #{ link_to '@ginnynumberone', 'https://www.twitter.com/ginnynumberone'} to talk about all things Ruby on Rails. I'm always looking to learn or hear feedback from experienced individuals in order to better myself.

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #errors
      %h2
        = "#{pluralize(@post.errors.count, "error")} prevented this post from saving"
          %ul
            - @post.errors.full_messages.each do |msg|
            %li
              = msg
  %p
    = f.label :title %br
    = f.text_field :title
  %p
    = f.label :body %br
    = f.text_area :body
  %p
    = f.submit "Share Post"

app/views/posts/edit.html.haml
#page_wrapper
	%h1 Edit Post
	= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
	.post_wrapper
		%h2.title
			= link_to post.title, post
		%p.date
			= post.created_at.strftime("%B, %d, %Y")

app/views/posts/new.html.haml
#page_wrapper
	%h1 New Post

	= render 'form'

app/views/posts/show.html.haml
#post_content
  %h1.title
    = @post.title 

  %p.date
    - "Submitted #{time_ago_in_words(@post.created_at)} ago."
    - if user_signed_in?
      = link_to 'Edit', edit_post_path(@post)
      = link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }

  %p.body
    = @post.body

  .comments
    %h2
    = "#{@post.comments.count} Comments."
    = render @post.comments

    %h3 
      Add a comment:
    = render "comments/form"